name: downlow
description: Easy to use Http Downloader (Supports continue file download, cancellation and more).
version: 0.1.1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
